Repository Worktez/worktez, pull requests merged in 2021-01, with the labels that each got.

#103 Feat/dark theme
  worktrolly-ui/src/app/body/board/board.component.css
  worktrolly-ui/src/app/body/board/feature-card/feature-card.component.html
  worktrolly-ui/src/app/body/board/sprint-details/sprint-details.component.css
  worktrolly-ui/src/app/body/board/sprint-details/sprint-details.component.html
  worktrolly-ui/src/app/body/body.component.css
  worktrolly-ui/src/app/body/create-new-session/create-new-session.component.css
  worktrolly-ui/src/app/body/create-new-session/create-new-session.component.html
  worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.css
  worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.html
  worktrolly-ui/src/app/body/filter-task/filter-task.component.css
  worktrolly-ui/src/app/body/filter-task/filter-task.component.html
  worktrolly-ui/src/app/body/loader/loader.component.css
  worktrolly-ui/src/app/body/login/login.component.css
  worktrolly-ui/src/app/body/my-dashboard/my-dashboard.component.css
  worktrolly-ui/src/app/body/my-dashboard/my-dashboard.component.html
  worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.css
  worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.html
  worktrolly-ui/src/app/body/task-details/log-work/log-work.component.css
  worktrolly-ui/src/app/body/task-details/log-work/log-work.component.html
  worktrolly-ui/src/app/body/task-details/task-details.component.css
  worktrolly-ui/src/app/body/task-details/task-details.component.html
  worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.css
  worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.html
  worktrolly-ui/src/app/body/tasks/tasks.component.css
  worktrolly-ui/src/app/header/header.component.css
  worktrolly-ui/src/app/header/header.component.html
  worktrolly-ui/src/app/header/login-handler/login-handler.component.css
  worktrolly-ui/src/app/header/login-handler/user-card/user-card.component.css
  worktrolly-ui/src/index.html
Labels: enhancement

#102 feat(Chart): Added Performance Chart Component
  worktrolly-ui/package-lock.json
  worktrolly-ui/package.json
  worktrolly-ui/src/app/app.module.ts
  worktrolly-ui/src/app/body/common-tools/chart/chart.component.css
  worktrolly-ui/src/app/body/common-tools/chart/chart.component.html
  worktrolly-ui/src/app/body/common-tools/chart/chart.component.spec.ts
  worktrolly-ui/src/app/body/common-tools/chart/chart.component.ts
  worktrolly-ui/src/app/body/loader/loader.component.html
  worktrolly-ui/src/app/body/my-dashboard/my-dashboard.component.css
  worktrolly-ui/src/app/body/my-dashboard/my-dashboard.component.html
  worktrolly-ui/src/app/body/my-dashboard/my-dashboard.component.ts
  worktrolly-ui/src/app/body/my-dashboard/my-tasks/my-tasks.component.css
  worktrolly-ui/src/app/body/my-dashboard/my-tasks/my-tasks.component.html
  worktrolly-ui/src/app/body/my-dashboard/my-tasks/my-tasks.component.spec.ts
  worktrolly-ui/src/app/body/my-dashboard/my-tasks/my-tasks.component.ts
  worktrolly-ui/src/app/body/my-dashboard/performance-chart/performance-chart.component.css
  worktrolly-ui/src/app/body/my-dashboard/performance-chart/performance-chart.component.html
  worktrolly-ui/src/app/body/my-dashboard/performance-chart/performance-chart.component.spec.ts
  worktrolly-ui/src/app/body/my-dashboard/performance-chart/performance-chart.component.ts
  worktrolly-ui/src/app/body/my-dashboard/performance-chart/range-card/range-card.component.css
  worktrolly-ui/src/app/body/my-dashboard/performance-chart/range-card/range-card.component.html
  worktrolly-ui/src/app/body/my-dashboard/performance-chart/range-card/range-card.component.spec.ts
  worktrolly-ui/src/app/body/my-dashboard/performance-chart/range-card/range-card.component.ts
  worktrolly-ui/src/app/body/task-details/task-details.component.css
  worktrolly-ui/src/app/services/backend.service.spec.ts
  worktrolly-ui/src/app/services/backend.service.ts
  worktrolly-ui/src/app/services/validation.service.ts
Labels: enhancement, feature

#99 fix taskcard ui
  worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.css
  worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.html
  worktrolly-ui/src/app/icons/priority-icons/priority-icons.component.css
  worktrolly-ui/src/app/icons/priority-icons/priority-icons.component.html
  worktrolly-ui/src/app/icons/status-icons/status-icons.component.css
  worktrolly-ui/src/app/icons/status-icons/status-icons.component.html
Labels: feature
