Repository Worktez/worktez, pull requests merged in 2022-10, with the labels that each got.

#747 fix(Assignee): fixed assignee dropdown task evaluation
  src/app/body/tasks-evaluation/task-ecard/task-ecard.component.css
  src/app/body/tasks-evaluation/task-ecard/task-ecard.component.html
Labels: bug, hacktoberfest

#757 fix(MyOrganization & social): fixed the edit logo in MyOrg and added indexing in techtag
  firestore.indexes.json
  functions/model/librarian/lib.js
  functions/model/librarian/librarian.js
  functions/model/librarian/tark/getFilesinOrganization.js
  src/app/app.component.html
  src/app/body/common-tools/update-image/update-image.component.ts
  src/app/body/profile/profile.component.html
  src/app/body/profile/profile.component.ts
  src/app/body/social-page/posts/posts.component.css
  src/app/body/social-page/posts/posts.component.html
  src/app/body/view-organization-details/edit-dp/edit-dp.component.css
  src/app/body/view-organization-details/edit-dp/edit-dp.component.html
  src/app/body/view-organization-details/edit-dp/edit-dp.component.ts
  src/app/body/view-organization-details/view-organization-details.component.html
  src/app/body/view-organization-details/view-organization-details.component.ts
  src/app/header/notification-center/notification-center.component.ts
  src/app/services/auth/auth.service.ts
  src/app/services/start/start-service.service.ts
Labels: hacktoberfest

#759 fix(my-org): fixed my organization functionalities and indexing for techtag
  functions/model/librarian/librarian.js
  functions/model/librarian/tark/getFilesInOrganizationLogo.js
Labels: hacktoberfest

#768 feat(createDefaultLabels): default labels tempelate
  functions/model/teams/tark/createDefaultLabels.js
  functions/model/teams/tark/createLabelProperties.js
  functions/model/teams/teams.js
  src/app/Interface/TeamLabelsTempelate.ts
  src/app/body/create-new-team/create-new-team.component.css
  src/app/body/create-new-team/create-new-team.component.html
  src/app/body/create-new-team/create-new-team.component.ts
  src/app/body/team-details/team-details.component.css
  src/app/body/team-details/team-details.component.html
  src/app/body/team-details/team-details.component.ts
Labels: feature, hacktoberfest

#766 UI of performance chart and skill card Done
  src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.css
  src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.html
  src/app/body/profile/profile.component.ts
  src/app/body/profile/skills/skills.component.html
Labels: enhancement, hacktoberfest

#775 Schedule Meet popup
  src/app/body/schedule-meet/schedule-meet.component.html
Labels: hacktoberfest

#772 fix(labelsUI)
  src/app/body/team-details/team-details.component.css
  src/app/body/team-details/team-details.component.html
  src/app/body/team-details/team-details.component.ts
Labels: hacktoberfest

#776 feat(razorpay):mechanism to change razorpay keys
  createRazorpayCred.js
Labels: hacktoberfest

#795 Fix(task-details):Fixed Comments Reload
  src/app/body/task-details/task-details.component.ts
Labels: hacktoberfest

#771 Create new team - validation
  functions/model/teams/tark/creatTeamIdCheck.js
  functions/model/teams/tark/createTeamNameCheck.js
  functions/model/teams/teams.js
  src/app/body/create-new-team/create-new-team.component.html
  src/app/body/create-new-team/create-new-team.component.ts
Labels: hacktoberfest

#785 Fix/contributors page
  functions/model/contributors/tark/addContributor.js
  src/app/Interface/UserInterface.ts
  src/app/body/contributors/add-contributors/add-contributors.component.css
  src/app/body/contributors/add-contributors/add-contributors.component.html
  src/app/body/contributors/add-contributors/add-contributors.component.ts
  src/app/body/contributors/contributors.component.css
  src/app/body/contributors/contributors.component.html
  src/app/body/contributors/contributors.component.ts
  src/app/body/filter-page/create-filter/create-filter.component.ts
  src/app/body/view-organization-details/org-documents/org-documents.component.css
  src/app/body/view-organization-details/org-documents/org-documents.component.html
Labels: hacktoberfest

#798 Fix/pricingPageDarkMode
  src/app/body/curren-plan/curren-plan.component.css
  src/app/body/curren-plan/curren-plan.component.html
Labels: hacktoberfest
