Repository Worktez/worktez, pull requests merged in 2022-07, with the labels that each got.

#617 Reload.new
  functions/model/mailer/lib.js
  src/app/body/board/board.component.ts
  src/app/body/tasks/tasks.component.ts
  src/environments/environment.ts
Labels: enhancement

#627 fix(Sort): Fixed Default Sort
  src/app/body/common-tools/data-table/data-table.component.html
  src/app/body/common-tools/data-table/data-table.component.ts
Labels: bug

#623 fix(DeleteLinks):provided an option to delete links
  functions/model/linker/lib.js
  functions/model/linker/linker.js
  functions/model/linker/tark/removeLink.js
  src/app/Interface/TasksInterface.ts
  src/app/body/task-details/task-details.component.html
  src/app/body/task-details/task-details.component.ts
Labels: feature

#625 fixed (gear icon) :Task details page
  src/app/body/view-organization-details/teams-card/teams-card.component.html
Labels: bug

#626 fixed (Comment Section ) bug
  src/app/body/task-details/task-details.component.html
Labels: bug

#629 feat(time): 'Added minutes algorithm to time'
  functions/model/tasks/tark/createTask.js
  functions/model/tasks/tark/editTask.js
  functions/model/tasks/tark/logwork.js
  src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.ts
  src/app/body/board/sprint-details/sprint-details.component.ts
  src/app/body/create-new-task/create-new-task.component.html
  src/app/body/create-new-task/create-new-task.component.ts
  src/app/body/task-details/edit-page/edit-page.component.html
  src/app/body/task-details/edit-page/edit-page.component.ts
  src/app/body/task-details/log-work/log-work.component.html
  src/app/body/task-details/log-work/log-work.component.ts
  src/app/body/task-details/task-details.component.css
  src/app/body/task-details/task-details.component.html
  src/app/body/task-details/task-details.component.ts
  src/app/services/tool/tools.service.ts
  src/app/services/validation/validation.service.ts
Labels: enhancement

#628 Fixed progress bar in Boards page
  functions/model/sprints/tark/updateSprintStatus.js
  src/app/body/board/sprint-details/sprint-details.component.ts
Labels: bug

#640 fix{iconAdded} : added plus icon in task details page {linksSection}
  src/app/body/task-details/task-details.component.html
Labels: enhancement

#639 fix{newTeam}:made Team id dynamic,validated emailid
  src/app/body/create-new-team/add-member/add-member.component.html
  src/app/body/create-new-team/add-member/add-member.component.ts
  src/app/body/create-new-team/create-new-team.component.html
  src/app/body/create-new-team/create-new-team.component.ts
Labels: enhancement

#647 Internal Release 6.2
  functions/model/users/lib.js
  src/app/Interface/UserInterface.ts
  src/app/body/common-tools/data-table/data-table.component.css
  src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.css
  src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.html
  src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.ts
  src/app/body/create-new-team/add-member/add-member.component.html
  src/app/body/create-new-team/add-member/add-member.component.ts
  src/app/body/create-new-team/create-new-team.component.html
  src/app/body/create-new-team/create-new-team.component.ts
  src/app/body/filter-task/filter-task.component.css
  src/app/body/home/home.component.css
  src/app/body/home/home.component.html
  src/app/body/home/home.component.ts
  src/app/body/home/testimonial-card/testimonial-card.component.css
  src/app/body/home/testimonial-card/testimonial-card.component.html
  src/app/body/home/testimonial-card/testimonial-card.component.ts
  src/app/body/kanban-board/kanban-board.component.ts
  src/app/body/milestone/milestone.component.css
  src/app/body/my-dashboard/my-tasks/my-tasks.component.css
  src/app/body/profile/edit-profile/edit-profile.component.html
  src/app/body/profile/profile.component.html
  src/app/body/profile/profile.component.ts
  src/app/body/social-page/posts/posts.component.html
  src/app/body/task-details/link/link.component.css
  src/app/body/task-details/link/link.component.html
  src/app/body/task-details/task-details.component.html
  src/app/body/tasks-evaluation/tasks-evaluation.component.ts
  src/app/body/view-organization-details/view-organization-details.component.css
  src/app/services/user-service/user-service.service.ts
  src/index.html
Labels: Internal Release
